name: .NET

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Generate PDF
      run: dotnet run
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          **/*.pdf
